version: "3"

services:
  expressmongodb:
    container_name: "NodeExpressMongoDBProd"
    image: sandrospengler/myexpressapp
    build:
      context: ${NodeExpressMongoDBProd}
      args:
        NODE_ENV: development
    ports:
      - "5000"
    environment:
      - NODE_ENV=${NODE_ENV}
      - DB_CONNECTION=${DB_CONNECTION}
      - VIRTUAL_HOST=expressmongo.localhost
      - LETSENCRYPT_HOST=expressmongo.localhost
    command: npm run prod

  expressmongo:
    container_name: "ExpressMongoProd"
    image: mongo:bionic
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ${MongoDBExpress}/data/db:/data/db
