version: "3"

services:
  expressmongodb:
    container_name: "NodeExpressMongoDBMain"
    image: sandrospengler/myexpressapp
    build:
      context: .
    environment:
      - PORT=5000
      - DB_CONNECTION=""
    networks:
      - ExpressMongoDBNetwork

  expressmongo:
    container_name: "ExpressMongoMain"
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=""
      - MONGO_INITDB_ROOT_PASSWORD=""
    volumes:
      - ~/mongo/data:/data/db
    networks:
      - ExpressMongoDBNetwork

networks:
  ExpressMongoDBNetwork:
